name: Python application testing

on:
  push:
    branches:
      - develop  # Runs on push to the develop branch
  pull_request:
    branches:
      - develop  # Runs on pull requests to the develop branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        python -m pytest test_app.py
